version: '3.4'
services:
  mercadito_db:
    container_name: mercadito_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mercadito_api
    ports:
      - '5432:5432'
