version: "3.3"
services:
  app:
    build: ./app
    command: nodemon server.js
    volumes:
      - ./app:/app
    ports:
      - "9000:9000"
  db:
    image: postgres:9.4-alpine
    container_name: db