// UP
const up = `CREATE TABLE PRODUCT (
  ID UUID NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  FK_CATEGORY_ID UUID NOT NULL REFERENCES CATEGORY(ID),
  FK_STOCK_ID UUID NOT NULL REFERENCES STOCK(ID),
  PRODUCT_NAME TEXT NOT NULL,
  PRODUCT_PRICE TEXT NOT NULL,
  PRODUCT_DESCRIPTION TEXT NOT NULL,
  CREATEDAT TIMESTAMP NOT NULL,
  UPDATEDAT TIMESTAMP DEFAULT NULL,
  DELETEDAT TIMESTAMP DEFAULT NULL
);`;

// DOWN
const down = `DROP TABLE PRODUCT;`;

module.exports = { up, down };
