// UP
const up = `CREATE TABLE CLIENT (
  ID UUID NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  ADDRESS_ID UUID NOT NULL REFERENCES ADDRESS(ID),
  NAME TEXT NOT NULL,
  LASTNAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  STREET TEXT NOT NULL,
  STREET_NUMBER TEXT NOT NULL,
  COMUNE TEXT NOT NULL,
  CITY TEXT NOT NULL,
  REGION TEXT NOT NULL,
  CREATEDAT TIMESTAMP NOT NULL,
  UPDATEDAT TIMESTAMP DEFAULT NULL,
  DELETEDAT TIMESTAMP DEFAULT NULL
);`;

// DOWN
const down = `DROP TABLE CLIENT`;

module.exports = { up, down };
